### ISSUE TITLE
Renko set_brick_size calls atr method which then throws an error from pandas on mismatched series lengths

### ISSUE THREAD

**Issue by jonfreedman** [carlfarterson/TAcharts#14]
I think the root cause of this is passing in a Pandas Series rather than a Numpy array here: https://github.com/carlfarterson/TAcharts/blob/master/TAcharts/indicators/renko.py#L54

See also:
@byteatwork in https://github.com/carlfarterson/TAcharts/issues/6#issuecomment-688618444_

**Comment by arul67800** [comment]
ValueError: Length of passed values is 7940, index implies 7939...Since you are shifting the dates by 1..it throws error..need change in core formula

**Comment by jonfreedman** [comment]
That particular error is now cleared, however we still can't plot a Renko chart, now I see the following error from https://github.com/carlfarterson/TAcharts/blob/master/TAcharts/wrappers.py#L34:

```
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by gambitov** [comment]
Dear @jonfreedman, could you solve this issue?

**Comment by jonfreedman** [comment]
I'm afraid I no longer work with the team who were attempting to use this functionality so I can't comment on any workarounds
