### ISSUE TITLE
NameError: name 'sma' is not defined

### ISSUE THREAD

**Issue by artaasd95** [carlfarterson/TAcharts#2]
You have used sma in the [ichimoku](https://github.com/carlfarterson/TAcharts/blob/master/TAcharts/indicators/ichimoku.py), but you did not import it. Please import it.
full traceback:
`in 
      1 i = ichimoku(data, interval=1)
----> 2 i.build(20, 60, 120, 30)

~\.conda\envs\djg\lib\site-packages\TAcharts\indicators\ichimoku.py in build(self, tenkan_interval, kijun_interval, senkou_b_interval, displacement)
     78         # Tenkan (conversion line) = (highest high + highest low)/2 for the past x intervals
     79         # Kijun (base line) = (highest high + lowest low)/2 for the past x*3 intervals
---> 80         self._build_lines(tenkan=tenkan_interval, kijun=kijun_interval)
     81 
     82         # Chikou (lagging span) = Current closing price time-shifted backwards x*3 intervals

~\.conda\envs\djg\lib\site-packages\TAcharts\indicators\ichimoku.py in _build_lines(self, **kwargs)
     48     def _build_lines(self, **kwargs):
     49         for key, val in kwargs.items():
---> 50             high = sma(self.df['high'], val, 'max')
     51             low = sma(self.df['low'], val, 'min')
     52             self.ichimoku[key] = (high + low)/2

NameError: name 'sma' is not defined`

**Comment by pegahcarter** [comment]
Just pushed changes in v0.0.21 and it should work now.
