### ISSUE TITLE
Ichimoku needs interval argument defined

### ISSUE THREAD

**Issue by jhmenke** [carlfarterson/TAcharts#3]
Running the Ichimoku example does not work right, the interval argument for Ichimoku cannot be None apparently :

>   File "C:/Users/Jan/PycharmProjects/stock_analysis/stock_chart_example.py", line 108, in altair_chart
>     i = Ichimoku(df)
>   File "C:\Users\Jan\Anaconda3\lib\site-packages\TAcharts\indicators\ichimoku.py", line 37, in __init__
>     self._validate_data(interval)
>   File "C:\Users\Jan\Anaconda3\lib\site-packages\TAcharts\indicators\ichimoku.py", line 42, in _validate_data
>     if interval > len(self.df):
> TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by pegahcarter** [comment]
Just updated, found the problem hidden in `bollinger.py`, too.  `pip uninstall TAcharts` and `pip install TAcharts` and you should be good to go!

**Comment by jhmenke** [comment]
thanks!
