### ISSUE TITLE
atr renko problems

### ISSUE THREAD

**Issue by gaju432** [carlfarterson/TAcharts#5]
Sir,

from TAcharts.indicators.renko import Renko

r = Renko(df)
r.set_brick_size(auto=True, atr_period=2)
r.build()

r.plot()

atr_period not found 
get error
  File "C:\ProgramData\Anaconda3\lib\site-packages\kiteconnect\ticker.py", line 71, in onMessage
    self.factory.on_message(self, payload, is_binary)
  File "C:\ProgramData\Anaconda3\lib\site-packages\kiteconnect\ticker.py", line 670, in _on_message
    self.on_ticks(self, self._parse_binary(payload))
  File "E:\crsitry\ta\tachartsrenko.py", line 156, in on_ticks
    r.set_brick_size(auto=True, atr_period=2)
builtins.TypeError: set_brick_size() got an unexpected keyword argument 'atr_period'

your base sample file not looking properly

please solve this and rectify this code for live tick data fro websocket

**Comment by pegahcarter** [comment]
Gotcha, it's a simple error in documentation.  Instead of `atr_period` it should be `atr_interval`

**Comment by pegahcarter** [comment]
https://github.com/carlfarterson/TAcharts/commit/8f4e00fd2bcd03300bdef39170a7faf9b65c9458
